FROM nginx:latest
RUN echo "Hell from nginx v1" > /usr/share/nginx/html/index.html
RUN echo "Adding Feature 1" >> /usr/share/nginx/html/index.html
RUN echo "Adding Feature 2" >> /usr/share/nginx/html/index.html
RUN echo "Adding Feature 3" >> /usr/share/nginx/html/index.html